version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    depends_on:
      - jupyter
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

    networks:
      - kafka-net

  jupyter:
    build: .
    ports:
      - 5000:8888
    environment:
      - JUPYTER_TOKEN=password
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # command: bash -c "./opt/kafka/bin/kafka-topics.sh --create --topic quickstart-events --bootstrap-server CLIENT://kafka:9092"

    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
# services:
#   zookeeper:
#     image: wurstmeister/zookeeper
#     container_name: zookeeper
#     ports:
#       - '2181:2181'
#     networks:
#       - kafka-net
#   jupyter:
#     build: .
#     ports:
#       - 5000:8888
#     networks:
#       - kafka-net

#   kafka:
#     image: wurstmeister/kafka
#     ports:
#       - 29092:29092
#     environment:
#       KAFKA_BROKER_ID: 1

#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9093
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9093
#       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#       KAFKA_PROCESS_ROLES: 'broker,controller'
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_CREATE_TOPICS: 'mytopic:1:1'

#     command: bash -c "./opt/kafka_2.13-2.8.1/bin/kafka-cluster.sh cluster-id --bootstrap-server OUTSIDE://0.0.0.0:9093 && KAFKA_CLUSTER_ID='$(./opt/kafka_2.13-2.8.1/bin/kafka-cluster.sh cluster-id --bootstrap-server zookeeper:2181)' && ./opt/kafka_2.13-2.8.1/bin/kafka-storage.sh format -t KAFKA_CLUSTER_ID -c ./opt/kafka_2.13-2.8.1/config/server.properties"
#     networks:
#       - kafka-net
# networks:
#   kafka-net:
#     driver: bridge
